-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/Nfihth/IKD98akH
Xpovh0swz4IfCAEsQ3OMc73aWvGgCgYIKoZIzj0DAQehRANCAATujvqzuwDGyuE3
y15KicbMSPNeWN67DyqKjHV4x5ZTaXyJqxLDPl9yPDK5Y+griVeAjns/S+JOFTO5
Zh7z3DcQ
-----END PRIVATE KEY-----